[package]
name = "richard"
version = "0.1.0"
authors = ["Jérôme Jutteau <jerome.jutteau@outscale.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clokwerk = "0.3.4"
env_logger = "0.10.0"
feed-rs = "1.2.0"
log = "0.4.17"
rand = "0.8.2"
serde = {version = "1.0.120", features = ["derive"]}
serde_json = "1.0.61"
ureq = {version = "2.0.2", features = ["json"]}
