// Quotes from https://en.wikiquote.org/wiki/Richard_Stallman
// Creative Commons Attribution-ShareAlike License
[
    "GNU, which stands for Gnu's Not Unix, is the name for the complete Unix-compatible software system which I am writing so that I can give it away free to everyone who can use it.",
    "To avoid horrible confusion, please pronounce the G in the word GNU when it is the name of this project.",
    "I consider that the golden rule requires that if I like a program I must share it with other people who like it.",
    "GNU is not in the public domain. Everyone will be permitted to modify and redistribute GNU, but no distributor will be allowed to restrict its further redistribution.",
    "Once GNU is written, everyone will be able to obtain good system software free, just like air.",
    "A hacker is someone who enjoys playful cleverness — not necessarily with computers.",
    "The use of “hacker” to mean “security breaker” is a confusion on the part of the mass media. We hackers refuse to recognize that meaning, and continue using the word to mean someone who loves to program, someone who enjoys playful cleverness, or the combination of the two.",
    "If we are content with knowledge as a commodity, accessible only through a computerized bureaucracy, we can simply let companies provide it. But if we want to keep human knowledge open and freely available to humanity, we have to do the work to make it available that way. We have to write a free encyclopedia.",
    "Very ironic things have happened, but nothing to match this — giving the Linus Torvalds Award to the Free Software Foundation is sort of like giving the Han Solo Award to the Rebel Fleet.",
    "Every decision a person makes stems from the person's values and goals. People can have many different goals and values; fame, profit, love, survival, fun, and freedom, are just some of the goals that a good person might have. When the goal is to help others as well as oneself, we call that idealism.
My work on free software is motivated by an idealistic goal: spreading freedom and cooperation. I want to encourage free software to spread, replacing proprietary software that forbids cooperation, and thus make our society better.",
    "While free software by any other name would give you the same freedom, it makes a big difference which name we use: different words convey different ideas.",
    "We are not against the Open Source movement, but we don't want to be lumped in with them. We acknowledge that they have contributed to our community, but we created this community, and we want people to know this.",
    "The term \"free software\" has an ambiguity problem: an unintended meaning, \"Software you can get for zero price,\" fits the term just as well as the intended meaning, \"software which gives the user certain freedoms.\" We address this problem by publishing a more precise definition of free software, but this is not a perfect solution; it cannot completely eliminate the problem. An unambiguously correct term would be better, if it didn't have other problems.",
    "The official definition of \"open source software,\" as published by the Open Source Initiative, is very close to our definition of free software; however, it is a little looser in some respects, and they have accepted a few licenses that we consider unacceptably restrictive of the users.",
    "Value your freedom or you will lose it, teaches history. \"Don't bother us with politics,\" respond those who don't want to learn.",
    "Geeks like to think that they can ignore politics, you can leave politics alone, but politics won't leave you alone.",
    "Thanks to Mr. Gates, we now know that an open Internet with protocols anyone can implement is communism; it was set up by that famous communist agent, the US Department of Defense.",
    "People said I should accept the world. Bullshit! I don't accept the world.",
    "You can use any editor you want, but remember that vi vi vi is the text editor of the beast.",
    "For personal reasons, I do not browse the web from my computer.",
    "I have to explain that I'm not an anarchist – I have a pro-state gland.",
    "Isn't it ironic that the proprietary software developers call us communists? We are the ones who have provided for a free market, where they allow only monopoly.",
    "The GNU GPL was not designed to be \"open source\". I wrote it for the free software movement, and its purpose is to ensure every user of every version of the program gets the essential freedoms. See http://www.gnu.org/philosophy/open-source-misses-the-point.html for more explanation of the difference between free software and open source.",
    "For personal reasons, I do not browse the web from my computer. (I also have no net connection much of the time.) To look at page I send mail to a daemon which runs wget and mails the page back to me. It is very efficient use of my time, but it is slow in real time.",
    "Corporations don't have to be decent. Real persons, if they do something that's lawful but nasty you'll say 'you are a jerk, you are acting like a jerk, stop it!'. But we are not supposed to ever say that to these phony people. We are supposed to say 'oh well, it's lawful so we'll just have to suffer it'.
",
    "Nobody deserves to have to die — not Jobs, not Mr. Bill, not even people guilty of bigger evils than theirs. But we all deserve the end of Jobs' malign influence on people's computing.",
    "It doesn't take special talents to reproduce — even plants can do it. On the other hand, contributing to a program like Emacs takes real skill. That is really something to be proud of. It helps more people, too.",
    "I am a pessimist by nature. Many people can only keep on fighting when they expect to win. I'm not like that, I always expect to lose. I fight anyway, and sometimes I win.",
    "Fighting patents one by one will never eliminate the danger of software patents, any more than swatting mosquitoes will eliminate malaria.",
    "Free software permits students to learn how software works. Some students, on reaching their teens, want to learn everything there is to know about their computer and its software. They are intensely curious to read the source code of the programs that they use every day. To learn to write good code, students need to read lots of code and write lots of code. They need to read and understand real programs that people really use. Only free software permits this.
Proprietary software rejects their thirst for knowledge: it says, “The knowledge you want is a secret — learning is forbidden!” Free software encourages everyone to learn. The free software community rejects the “priesthood of technology”, which keeps the general public in ignorance of how technology works; we encourage students of any age and situation to read the source code and learn as much as they want to know. Schools that use free software will enable gifted programming students to advance.",
    "It is hard to write a simple definition of something as varied as hacking, but I think what these activities have in common is playfulness, cleverness, and exploration. Thus, hacking means exploring the limits of what is possible, in a spirit of playful cleverness. Activities that display playful cleverness have 'hack value'.",
    "People sometimes ask me if it is a sin in the Church of Emacs to use vi. Using a free version of vi is not a sin; it is a penance. So happy hacking.",
    "I could have made money this way, and perhaps amused myself writing code. But I knew that at the end of my career, I would look back on years of building walls to divide people, and feel I had spent my life making the world a worse place.",
    "Stallman's Law (2012): While corporations dominate society and write the laws, each advance in technology is an opening for them to further restrict its users.",
    "I did write some code in Java once, but that was the island in Indonesia.",
    "People have a tendancy to be very scared of terrorists and not so scared of cars. But cars are a much bigger danger. The US declares war on terrorism. The cars have been killing thousands of Americans and still we don’t have a global war on cars. People are bad judges of how important various dangers are.",
]
